config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sweets#index'
  resources :users, only: [:show, :index, :edit, :update]
  resources :sweets, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resources :sweet_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :notifications, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :sweet
end

app/models/notification.rb
class Notification < ApplicationRecord
  #スコープ(新着順)
  default_scope->{order(created_at: :desc)}

  belongs_to :sweet, optional: true
  belongs_to :comment, optional: true
  belongs_to :visiter, class_name: 'User', foreign_key: 'visiter_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/models/sweet.rb
class Sweet < ApplicationRecord
  belongs_to :user
  has_many :sweet_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  attachment :sweet_image
  #バリデーション
  validates :name, presence: true
  validates :opinion, presence: true, length: { maximum:200 }
  validates :sweet_image, presence: true
end

app/models/sweet_comment.rb
class SweetComment < ApplicationRecord
  belongs_to :user
  belongs_to :sweet
  #バリデーション
  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :sweets, dependent: :destroy
  has_many :sweet_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :user_image
  #バリデーション
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #deviseの画面を用いる場合記述
  before_action :configure_permitted_parameters, if: :devise_controller?
  #devise版ストロングパラメータみたいなもの
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @sweet = Sweet.find(params[:sweet_id])
    favorite = current_user.favorites.new(sweet_id: @sweet.id)
    favorite.save
    @sweet.create_notification_by(current_user)
    redirect_to request.referer
  end
  def destroy
    sweet = Sweet.find(params[:sweet_id])
    favorite = current_user.favorites.find_by(sweet_id: sweet.id)
    favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    #current_userの投稿に紐づいた通知一覧
    @notifiation = current_user.passive_notifications
    #@notificationの中でまだ確認していない(indexに一度も遷移していない)通知のみ
    @notifiation.where(checked: false).each do |notifiation|
      notifiation.update_attributes(checked: true)
    end
  end
  def destroy_all
    #通知を全削除
    @notifiations = current_user.passive_notifications.destroy_all
    redirect_to users_notifications_path
  end
end

app/controllers/sweet_comments_controller.rb
class SweetCommentsController < ApplicationController
#コメント作成メソッド
  def create
    @sweet = Sweet.find(params[:sweet_id])
    @sweet_comment = SweetComment.new
    @q = Sweet.ransack(params[:q])
    @sweets = @q.result(distinct: true)
    @comment = current_user.sweet_comments.new(sweet_comment_params)
    @comment.sweet_id = @sweet.id
    #if @comment.save
      @comment.save
      redirect_to sweet_path(@sweet)
    #else
    #  render 'sweets/show'
    #end
  end
#コメント投稿時のストロングパラメータ
  private
  def sweet_comment_params
    params.require(:sweet_comment).permit(:comment)
  end
end

app/controllers/sweets_controller.rb
class SweetsController < ApplicationController
  #未ログイン時、指定ページへ移動不可
  before_action :authenticate_user!, only: [:edit, :create, :new]
  #編集URL直打ち防止
  before_action :correct_user, only: [:edit, :update]
  #おかし新規登録ページの表示
  def new
    @sweet = Sweet.new
    @q = Sweet.ransack(params[:q])
    @sweets = @q.result(distinct: true)
  end
  #おかしの新規作成
  def create
    @sweet = current_user.sweets.new(sweet_params)
    @sweet.user_id = current_user.id
    @q = Sweet.ransack(params[:q])
    @sweets = @q.result(distinct: true)
    if @sweet.save
      redirect_to sweets_path
    else
      render :new
    end
  end
  #おかし一覧
  def index
    #@sweets = Sweet.all
    #おかし検索(allも含む)
    @q = Sweet.ransack(params[:q])
    @sweets = @q.result(distinct: true)
    #いいねランキング
    @all_ranks = Sweet.find(Favorite.group(:sweet_id).order('count(sweet_id) desc').limit(3).pluck(:sweet_id))
  end
  #おかし詳細
  def show
    @sweet = Sweet.find(params[:id])
    @sweet_comment = SweetComment.new
    @q = Sweet.ransack(params[:q])
    @sweets = @q.result(distinct: true)
  end
  #おかし編集表示
  def edit
    @sweet = Sweet.find(params[:id])
    @q = Sweet.ransack(params[:q])
    @sweets = @q.result(distinct: true)
  end
  #おかし編集
  def update
    sweet = Sweet.find(params[:id])
    sweet.update(sweet_params)
    redirect_to sweet_path
  end
  #おかし削除
  def destroy
    sweet = Sweet.find(params[:id])
    sweet.destroy
    redirect_to sweets_path
  end

  private
    #おかし投稿時のストロングパラメータ
    def sweet_params
      params.require(:sweet).permit(:name, :opinion, :sweet_image, :tag_list)
    end
    #編集URL直打ち防止メソッド
    def correct_user
      @sweet = Sweet.find(params[:id])
      unless @sweet.user.id == current_user.id
        redirect_to sweets_path
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  def show
    @user = User.find(params[:id])
    @q = Sweet.ransack(params[:q])
    @sweets = @q.result(distinct: true)
  end
  def edit
    if
      @user = current_user
    else
       render :show
    end
    @q = Sweet.ransack(params[:q])
    @sweets = @q.result(distinct: true)
  end
  def update
    user = current_user
    if user.update(user_params)
       redirect_to user_path(user.id)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :opinion, :user_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def notification_form(notification)
    @visiter = notification.visiter
    #@comment sweet = nil
    your_ = link_to 'あなたの投稿', users_sweet_path(notification), style:"font-weight: bold;"
    @visiter_comment = notification.comment_id
    #notification.actionがfollowかlikeかcommentか
    case notification.action
      when "follow" then
        tag.a(notification.visiter.name, href:users_user_path(@visiter), style:"font-weight: bold;")+"があなたをフォローしました"
      when "like" then
        tag.a(notification.visiter.name, href:users_user_path(@visiter), style:"font-weight: bold;")+"が"+tag.a('あなたの投稿', href:users_sweet_path(notification.sweet_id), style:"font-weight: bold;")+"にいいねしました"
      when "comment" then
          @comment = Comment.find_by(id: @visiter_comment)&.content
          tag.a(@visiter.name, href:users_user_path(@visiter), style:"font-weight: bold;")+"が"+tag.a('あなたの投稿', href:users_sweet_path(notification.sweet_id), style:"font-weight: bold;")+"にコメントしました"
    end
  end
end

app/helpers/sweet_comments_helper.rb
module SweetCommentsHelper
end

app/helpers/sweets_helper.rb
module SweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <span class="info-title">
      <%= model.errors.count %>errors prohibited this obj from being saved:
    </span>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Switter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="sweet-content">
      <div class="sweet">
        <header>
          <div class="container">
            <div class="row">
              <h1 class="title">
                <%= link_to "Switter", sweets_path, :style=>"color:#FFF;" %>
              </h1>
              <ul class="ul-header">
                <% if user_signed_in? %>
                  <li class="header">
                    <%= link_to "プロフィール", user_path(current_user), :style=>"color:#FFF;" %>
                  </li>
                  <li class="header">
                    <%= link_to "ログアウト", destroy_user_session_path, method: :delete, :style=>"color:#FFF;" %>
                  </li>
                <% else %>
                  <li class="header">
                    <%= link_to "会員登録", new_user_registration_path, :style=>"color:#FFF;" %>
                  </li>
                  <li class="header">
                    <%= link_to "ログイン", new_user_session_path, :style=>"color:#FFF;" %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </header>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/notifications/_notification.html.erb
<% visiter = notification.visiter %>
<% sweet = notification.sweet %>

<div class="user-view clearfix ">
  <%= link_to users_user_path(notification.visiter) do %>
    <%= attachment_image_tag visiter, :profile_image, :fill,100,100, format: "jpeg", fallback: "no_image.jpg", size: "50x50", class:"profile-img-circle" %>
  <% end %>
  <%= notification_form(notification) %><span class="moderate-font"><%= " (#{time_ago_in_words(notification.created_at)} 前)" %></span>
  <br>
  <% if !@comment.nil? %>
    <p class="moderate-font text-center" style="color: #C0C0C0;"><%= @comment %></p>
  <% end %>
</div>

app/views/notifications/index.html.erb
<h3 class="text-center">通知</h3>
    <!--= link_to destroy_all_users_notifications_path, method: :delete do %-->
        <i class="fas fa-trash" style="color: black;"></i>
        <h7 style="color: black;">全削除</h7>
    <!-- end %-->
    <hr>
<% if @notifications.exists? %>
    <div class="users-index">
        <%= render @notifications %>
    </div>
<% else %>
    <p>通知はありません</p>
<% end %>

app/views/sweets/_list.html.erb
<% sweets.each do |sweet| %>
  <div class="masonry-block">
    <div class="block block-image v1">
      <div class="block-image">
        <div class="view view-first">
          <%= link_to sweet_path(sweet.id), method: :get do %>
            <%= attachment_image_tag sweet, :sweet_image, format: 'jpeg', fallback:"no_image2.jpg", class: "index-img" %>
          <% end %>
        </div>
      </div>
      <div class="sweet-link">
        <h4 class="sweet-info">
          <%= link_to sweet.name, sweet_path(sweet.id) %>
        </h4>
        <li class="sweet-info">
          <i class="far fa-comments"></i>
          <%= sweet.sweet_comments.count %>
        </li>
        <!-- ユーザーがログインしてたら -->
        <% if user_signed_in? %>
          <!-- いいね表示 -->
          <% if sweet.favorited_by?(current_user) %>
            <!-- いいねあるとき -->
            <li class="sweet-info">
              <%= link_to sweet_favorites_path(sweet), method: :delete do %>
                <i class="fas fa-heart"></i>
                <%= sweet.favorites.count %>
              <% end %>
            </li>
          <% else %>
            <!-- いいねないとき -->
            <li class="sweet-info">
              <%= link_to sweet_favorites_path(sweet), method: :post do %>
                <i class="far fa-heart"></i>
                <%= sweet.favorites.count %>
              <% end %>
            </li>
          <% end %>
        <% else %><!-- ログインしてないとき -->
          <li class="sweet-info">
            <i class="far fa-heart"></i>
            <%= sweet.favorites.count %>
          </li>
        <% end %>
        <li>
          <% sweet.tag_list.each do |tag| %>
            <%= tag %>
          <% end %>
        </li>
      </div>
      <hr class="index-line">
    </div>
  </div>
<% end %>

app/views/sweets/_newbtn.html.erb
  <!-- ユーザーがログインしてたら -->
  <% if user_signed_in? %>
    <div class="sweet-new-btn">
      <%= link_to new_sweet_path, method: :get do %>
        <i class="fas fa-plus-circle fa-3x"></i>
      <% end %>
    </div>
  <% else %>
  <% end %>

app/views/sweets/_search.html.erb
<div class="search">
  <!-- 検索バー -->
  <%= search_form_for q do |f| %>
    <!-- f.label :name, "Keyword" %-->
    <%= f.search_field :name_or_opinion_cont, placeholder:"おかし検索"  %>
      <%= button_tag :type => "submit", :class =>"search-btn" do %>
        <i class="fas fa-search"></i>
      <% end %>
  <% end %>
  <%= link_to "検索クリア", sweets_path %>
</div>

app/views/sweets/edit.html.erb
<div class="container">
  <div class="row">
    <div class="sweet-body">
    <%= render 'layouts/error_messages', model: @sweet %>
      <div class="col-xs-9">
        <h2>Edit Sweet</h2>
        <%= form_for(@sweet, url: sweet_path) do |f| %>
          <div class="">
            <%= f.text_field :name %>
          </div>
          <div class="">
            <%= f.text_area :opinion %>
          </div>
          <div class="">
            <%= f.attachment_field :sweet_image %>
          </div>
          <!--div class="">
            <= text_field_tag 'sweet[tag_list]', @sweet.tag_list.join(","), placeholder:"タグ" %>
          </div-->
          <%= f.submit '変更保存' %>
        <% end %>
      </div>
      <div class="col-xs-1">
        <%= render 'sweets/newbtn' %>
      </div>
      <div class="col-xs-2">
        <%= render 'sweets/search', q: @q %>
      </div>
    </div>
  </div>
</div>

app/views/sweets/index.html.erb
<div class="container">
  <div class="row">
    <!-- カテゴリとランキングはrender -->
    <!--div class="sweet-body">
      <div class="col-xs-3">
        <div class="favorite-ranking">
          <-- ランキング >
          <h2>いいねランキング</h2>
          <table class="">
            <thead>
              <tr>
                <th class=""></th>
                <th class=""></th>
              </tr>
            </thead>
            <tbody>
              <-- render 'sweets/table', sweets: @all_ranks %>
            </tbody>
          </table>
        </div>
      </div>
    </div-->
    <div class="col-xs-9">
      <div class="sweets-index">
        <!-- 一覧部分 -->
        <h2 class="index-title">全投稿</h2>
        <%= sort_link(@q, :name, "おかし名ソート") %>
        <%= render 'sweets/list', sweets: @sweets %>
      </div>
    </div>
    <div class="col-xs-1">
      <%= render 'sweets/newbtn' %>
    </div>
    <div class="col-xs-2">
      <%= render 'sweets/search', q: @q %>
    </div>
  </div>
</div>

app/views/sweets/new.html.erb
<div class="container">
  <div class="row">
    <%= render 'layouts/error_messages', model: @sweet %>
    <div class="col-xs-10">
      <div class="sweet-body">
        <h2>おかし投稿</h2>
        <%= form_for(@sweet, url: sweets_path) do |f| %>
          <div class="">
            <!-- f.label :name, "おかし名" -->
            <%= f.text_field :name, placeholder:"おかし名" %>
          </div>
          <div class="">
            <!-- f.label :opinion, "おかし説明" -->
            <%= f.text_area :opinion, placeholder:"おかし説明" %>
          </div>
          <div class="">
            <%= f.attachment_field :sweet_image %>
          </div>
          <div class="">
            <!--= f.label :タグ %>
            <= text_field_tag 'sweet[tag_list]', @sweet.tag_list.join(",") %-->
          </div>
          <%= f.submit '登録' %>
        <% end %>
      </div>
    </div>
    <div class="col-xs-2">
      <%= render 'sweets/search', q: @q %>
    </div>
  </div>
</div>

app/views/sweets/show.html.erb
<div class="container">
  <div class="row">
    <div class="sweet-body">
    <%= render 'layouts/error_messages', model: @sweet_comment %>
      <div class="col-xs-6">
        <h2><%= @sweet.name %></h2>
        <!-- @sweet.tag_list.each do |tag| %>
          <= tag %-->
        <!-- end %-->
        <p><%= @sweet.opinion %></p>
        <%= attachment_image_tag @sweet, :sweet_image, format: 'jpeg', fallback:"no_image2.jpg", class: "img" %>
        <!-- もしログインしていて投稿ユーザーであれば表示 --><br>
        <% if user_signed_in? %>
          <% if @sweet.user == current_user %>
            <%= link_to "Edit", edit_sweet_path(@sweet.id) %>
            <%= link_to "Destroy", sweet_path(@sweet.id), method: :delete, data: { confirm: "本当に消しますか？" } %>
          <% end %>
        <% else %>
        <% end %>
      </div>
      <div class="col-xs-3">
        <!-- コメント表示 --><br>
        <% @sweet.sweet_comments.each do |sweet_comment| %>
          <%= attachment_image_tag sweet_comment.user, :user_image, format: 'jpeg', size: "40x40", fallback: "no_image.jpg", class: "img-circle pull-left profile-thumb" %>
          <li class="show-li">
            <%= link_to user_path(sweet_comment.user) do %>
              <%= sweet_comment.user.name %>
            <% end %>
          </li>
          <li class="show-li">
            コメント：<%= sweet_comment.comment %>
          </li><br>
        <% end %>
        <!-- コメント投稿 -->
        <%= form_for [@sweet, @sweet_comment] do |f| %>
          <div class="">
            <%= f.text_area :comment, placeholder: "コメント" %>
          </div>
          <%= f.submit "送信" %>
        <% end %>
      </div>
      <div class="col-xs-1">
        <%= render 'sweets/newbtn' %>
      </div>
      <div class="col-xs-2">
        <%= render 'sweets/search', q: @q %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="sweet-body">
      <div class="col-xs-9">
        <h2>会員情報編集</h2>
        <%= form_for(@user, url: user_path) do |f| %>
          <div class="">
            <%= f.text_field :name, placeholder:"ユーザー名" %>
          </div>
          <div class="">
            <%= f.text_area :opinion, placeholder:"自己紹介" %>
          </div>
          <div class="">
            <%= f.attachment_field :user_image %>
          </div>
          <%= f.submit '変更保存' %>
        <% end %>
      </div>
      <div class="col-xs-1">
        <%= render 'sweets/newbtn' %>
      </div>
      <div class="col-xs-2">
        <%= render 'sweets/search', q: @q %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h2>ユーザー一覧</h2>
<table class="">
  <thead>
    <tr>
      <th class="">見出し１</th>
      <th class="">見出し２</th>
      <th class="">見出し３</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td>
        <%= user.email %>
      </td>
      <td>
        <!-- user.introduction -->
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="sweet-body">
      <div class="col-xs-1">
        <div class="user-photo">
          <%= attachment_image_tag @user, :user_image, format: 'jpeg', size: "60x60", fallback: "no_image.jpg", class: "img-circle pull-left profile-thumb" %>
        </div>
      </div>
      <div class="col-xs-6">
        <h2><%= @user.name %></h2>
        <% if present? %><!-- もし存在していたら -->
          <%= @user.opinion %>
        <% end %>
        <!--h3>< @user.email %></h3-->
        <% if user_signed_in? %>
          <% if current_user %>
            <br><%= link_to "Edit", edit_user_path(current_user) %>
          <% end %>
        <% else %>
        <% end %>
      </div>
      <div class="col-xs-2">
        <!--p>Favorite</p-->
      </div>
      <div class="col-xs-1">
        <%= render 'sweets/newbtn' %>
      </div>
      <div class="col-xs-2">
        <%= render 'sweets/search', q: @q %>
      </div>
    </div>
  </div>
</div>